
package br.com.adsdevelopment.serasa.gestorcredito.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsgestordecisaoSoap", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsgestordecisaoSoap {


    /**
     * 
     * @param sScore
     * @param bAtualizar
     * @param sSociosCNPJ
     * @param sOnLine
     * @param sCNPJ
     * @param vrCompra
     * @param sDoc
     * @param iQuadroSocial
     * @param sPassSer
     * @param sSociosCPF
     * @param bSerasa
     * @param sIdSocios
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarCreditoS", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCreditoS")
    @WebResult(name = "AnalisarCreditoSResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCreditoS", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoS")
    @ResponseWrapper(localName = "AnalisarCreditoSResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoSResponse")
    public String analisarCreditoS(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        double vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine,
        @WebParam(name = "sSociosCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sSociosCNPJ,
        @WebParam(name = "sSociosCPF", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sSociosCPF,
        @WebParam(name = "sIdSocios", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sIdSocios,
        @WebParam(name = "iQuadroSocial", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        int iQuadroSocial);

    /**
     * 
     * @param sDoc
     * @param sScore
     * @param sPassSer
     * @param bAtualizar
     * @param bSerasa
     * @param sOnLine
     * @param sCNPJ
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @param vrCompra
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarCreditoTeste", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCreditoTeste")
    @WebResult(name = "AnalisarCreditoTesteResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCreditoTeste", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoTeste")
    @ResponseWrapper(localName = "AnalisarCreditoTesteResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoTesteResponse")
    public String analisarCreditoTeste(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        double vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine);

    /**
     * 
     * @param sDoc
     * @param sScore
     * @param sPassSer
     * @param bAtualizar
     * @param bSerasa
     * @param sOnLine
     * @param sCNPJ
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @param vrCompra
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarCredito", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCredito")
    @WebResult(name = "AnalisarCreditoResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCredito", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCredito")
    @ResponseWrapper(localName = "AnalisarCreditoResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoResponse")
    public String analisarCredito(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        double vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine);

    /**
     * 
     * @param sDoc
     * @param sScore
     * @param sPassSer
     * @param bAtualizar
     * @param bSerasa
     * @param sOnLine
     * @param sCNPJ
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @param vrCompra
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarCreditoLog", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCreditoLog")
    @WebResult(name = "AnalisarCreditoLogResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCreditoLog", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoLog")
    @ResponseWrapper(localName = "AnalisarCreditoLogResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoLogResponse")
    public String analisarCreditoLog(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        double vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/invokeIntegrationServiceFromSTS")
    @WebResult(name = "invokeIntegrationServiceFromSTSResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "invokeIntegrationServiceFromSTS", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.InvokeIntegrationServiceFromSTS")
    @ResponseWrapper(localName = "invokeIntegrationServiceFromSTSResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.InvokeIntegrationServiceFromSTSResponse")
    public String invokeIntegrationServiceFromSTS(
        @WebParam(name = "arg0", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String arg0);

    /**
     * 
     * @param sDoc
     * @param sScore
     * @param sPassSer
     * @param bAtualizar
     * @param bSerasa
     * @param sOnLine
     * @param sCNPJ
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @param vrCompra
     * @return
     *     returns br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoRelatorioRetorno
     */
    @WebMethod(operationName = "AnalisarCreditoRelatorio", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCreditoRelatorio")
    @WebResult(name = "AnalisarCreditoRelatorioResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCreditoRelatorio", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoRelatorio")
    @ResponseWrapper(localName = "AnalisarCreditoRelatorioResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoRelatorioResponse")
    public AnalisarCreditoRelatorioRetorno analisarCreditoRelatorio(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        double vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine);

    /**
     * 
     * @param coAdquirenteScore1
     * @param sScore
     * @param coAdquirenteScore3
     * @param coAdquirenteScore2
     * @param bAtualizar
     * @param coAdquirenteCPF3
     * @param coAdquirenteCPF4
     * @param coAdquirenteCPF5
     * @param sOnLine
     * @param sCNPJ
     * @param coAdquirenteScore5
     * @param coAdquirenteScore4
     * @param vrCompra
     * @param sDoc
     * @param sPassSer
     * @param coAdquirenteCPF1
     * @param coAdquirenteCPF2
     * @param bSerasa
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @return
     *     returns br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoRelatorioRetorno
     */
    @WebMethod(operationName = "AnalisarCreditoRelatorioCoAdquirente", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCreditoRelatorioCoAdquirente")
    @WebResult(name = "AnalisarCreditoRelatorioCoAdquirenteResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCreditoRelatorioCoAdquirente", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoRelatorioCoAdquirente")
    @ResponseWrapper(localName = "AnalisarCreditoRelatorioCoAdquirenteResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoRelatorioCoAdquirenteResponse")
    public AnalisarCreditoRelatorioRetorno analisarCreditoRelatorioCoAdquirente(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine,
        @WebParam(name = "CoAdquirenteCPF1", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteCPF1,
        @WebParam(name = "CoAdquirenteScore1", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteScore1,
        @WebParam(name = "CoAdquirenteCPF2", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteCPF2,
        @WebParam(name = "CoAdquirenteScore2", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteScore2,
        @WebParam(name = "CoAdquirenteCPF3", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteCPF3,
        @WebParam(name = "CoAdquirenteScore3", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteScore3,
        @WebParam(name = "CoAdquirenteCPF4", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteCPF4,
        @WebParam(name = "CoAdquirenteScore4", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteScore4,
        @WebParam(name = "CoAdquirenteCPF5", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteCPF5,
        @WebParam(name = "CoAdquirenteScore5", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String coAdquirenteScore5);

    /**
     * 
     * @param sDoc
     * @param sScore
     * @param sPassSer
     * @param bAtualizar
     * @param bSerasa
     * @param sOnLine
     * @param sCNPJ
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @param sCheque
     * @param vrCompra
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarCreditoCheque", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCreditoCheque")
    @WebResult(name = "AnalisarCreditoChequeResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCreditoCheque", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoCheque")
    @ResponseWrapper(localName = "AnalisarCreditoChequeResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoChequeResponse")
    public String analisarCreditoCheque(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        double vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine,
        @WebParam(name = "sCheque", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCheque);

    /**
     * 
     * @param sDoc
     * @param sScore
     * @param sPassSer
     * @param bAtualizar
     * @param bSerasa
     * @param sOnLine
     * @param sCNPJ
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @param vrCompra
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarCreditoW", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCreditoW")
    @WebResult(name = "AnalisarCreditoWResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCreditoW", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoW")
    @ResponseWrapper(localName = "AnalisarCreditoWResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoWResponse")
    public String analisarCreditoW(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        double vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine);

    /**
     * 
     * @param sPassSer
     * @param controleWF
     * @param sCNPJ
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GestorCreditoStatusWorkFlow", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/GestorCreditoStatusWorkFlow")
    @WebResult(name = "GestorCreditoStatusWorkFlowResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "GestorCreditoStatusWorkFlow", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.GestorCreditoStatusWorkFlow")
    @ResponseWrapper(localName = "GestorCreditoStatusWorkFlowResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.GestorCreditoStatusWorkFlowResponse")
    public String gestorCreditoStatusWorkFlow(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "ControleWF", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        long controleWF);

    /**
     * 
     * @param xmlEnvio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarCreditoXML", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCreditoXML")
    @WebResult(name = "AnalisarCreditoXMLResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCreditoXML", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoXML")
    @ResponseWrapper(localName = "AnalisarCreditoXMLResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCreditoXMLResponse")
    public String analisarCreditoXML(
        @WebParam(name = "XMLEnvio", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String xmlEnvio);

    /**
     * 
     * @param sXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarLote", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarLote")
    @WebResult(name = "AnalisarLoteResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarLote", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarLote")
    @ResponseWrapper(localName = "AnalisarLoteResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarLoteResponse")
    public String analisarLote(
        @WebParam(name = "sXML", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sXML);

    /**
     * 
     * @param cnpj
     * @param chaveArquivo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornoLote", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/RetornoLote")
    @WebResult(name = "RetornoLoteResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "RetornoLote", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.RetornoLote")
    @ResponseWrapper(localName = "RetornoLoteResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.RetornoLoteResponse")
    public String retornoLote(
        @WebParam(name = "CNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String cnpj,
        @WebParam(name = "ChaveArquivo", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String chaveArquivo);

    /**
     * 
     * @param usuarioSerasa
     * @param senhaGestor
     * @param usuarioGestor
     * @param senhaSerasa
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BuscaPolParametro", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/BuscaPolParametro")
    @WebResult(name = "BuscaPolParametroResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "BuscaPolParametro", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.BuscaPolParametro")
    @ResponseWrapper(localName = "BuscaPolParametroResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.BuscaPolParametroResponse")
    public String buscaPolParametro(
        @WebParam(name = "UsuarioGestor", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String usuarioGestor,
        @WebParam(name = "SenhaGestor", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String senhaGestor,
        @WebParam(name = "UsuarioSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String usuarioSerasa,
        @WebParam(name = "SenhaSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String senhaSerasa);

    /**
     * 
     * @param docConsultado
     * @param usuarioSerasa
     * @param senhaGestor
     * @param valorCompra
     * @param tipoDoc
     * @param dadoOnline
     * @param usuarioGestor
     * @param senhaSerasa
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarMobile", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarMobile")
    @WebResult(name = "AnalisarMobileResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarMobile", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarMobile")
    @ResponseWrapper(localName = "AnalisarMobileResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarMobileResponse")
    public String analisarMobile(
        @WebParam(name = "UsuarioGestor", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String usuarioGestor,
        @WebParam(name = "SenhaGestor", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String senhaGestor,
        @WebParam(name = "UsuarioSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String usuarioSerasa,
        @WebParam(name = "SenhaSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String senhaSerasa,
        @WebParam(name = "TipoDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String tipoDoc,
        @WebParam(name = "DocConsultado", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String docConsultado,
        @WebParam(name = "ValorCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        int valorCompra,
        @WebParam(name = "DadoOnline", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String dadoOnline);

    /**
     * 
     * @param sDoc
     * @param sScore
     * @param sPassSer
     * @param bAtualizar
     * @param bSerasa
     * @param sOnLine
     * @param sCNPJ
     * @param sUsrGC
     * @param sPassGC
     * @param sUsrSer
     * @param vrCompra
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalisarCrivo", action = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao/AnalisarCrivo")
    @WebResult(name = "AnalisarCrivoResult", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
    @RequestWrapper(localName = "AnalisarCrivo", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCrivo")
    @ResponseWrapper(localName = "AnalisarCrivoResponse", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao", className = "br.com.adsdevelopment.serasa.gestorcredito.soap.AnalisarCrivoResponse")
    public String analisarCrivo(
        @WebParam(name = "sCNPJ", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sCNPJ,
        @WebParam(name = "sUsrGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrGC,
        @WebParam(name = "sPassGC", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassGC,
        @WebParam(name = "sUsrSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sUsrSer,
        @WebParam(name = "sPassSer", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sPassSer,
        @WebParam(name = "sDoc", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sDoc,
        @WebParam(name = "VrCompra", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        double vrCompra,
        @WebParam(name = "sScore", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sScore,
        @WebParam(name = "bSerasa", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bSerasa,
        @WebParam(name = "bAtualizar", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        boolean bAtualizar,
        @WebParam(name = "sOnLine", targetNamespace = "https://sitenet05.serasa.com.br/wsgestordecisao/wsgestordecisao")
        String sOnLine);

}
